project:
  type: website

website:
  title: "Vsevolod Suschevskiy"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vvseva
      - icon: twitter
        href: https://twitter.com/vvsuschevskiy
      - icon: linkedin
        href: https://www.linkedin.com/in/vvsuschevskiy
format:
  html:
    theme: 
      - sketchy
      - sketchy_custom.scss
      # - quartz
    mainfont: "Lato"
    # css: styles.css

editor: visual

execute:
  freeze: auto
