project:
  type: website
  resources: 
    - CTEC-2025-SP-SNA.pdf
    - CTEC-2024-SP-SNA.pdf

website:
  title: "Vsevolod Suschevskiy"
  navbar:
    right:
      - projects.qmd
      - teaching.qmd
      - icon: github
        href: https://github.com/vvseva
        target: _blank
      - icon: twitter
        href: https://bsky.app/profile/vvseva.bsky.social
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/vvsuschevskiy
        target: _blank
  favicon: "icon/logo.png"
format:
  html:
    theme: 
      - litera
      - litera_custom.scss
      # - sketchy_custom.scss
      # - quartz
    # mainfont: "Source Serif 4"
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" type="text/css"/>
    # css: styles.css
mainfont: "Source Serif 4"
editor: visual

execute:
  freeze: true
