project:
  type: website

website:
  title: "Vsevolod Suschevskiy"
  navbar:
    right:
      - projects.qmd
      - teaching.qmd
      - icon: github
        href: https://github.com/vvseva
        target: _blank
      - icon: blusky
        href: https://bsky.app/profile/vvseva.bsky.social
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/vvsuschevskiy
        target: _blank
  favicon: "icon/logo.png"
format:
  html:
    theme: 
      - litera
      - litera_custom.scss
      # - sketchy_custom.scss
      # - quartz
    mainfont: "Source Serif 4"
    # css: styles.css

editor: visual

execute:
  freeze: true
